services:
  - type: web
    name: as-gastronomico-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: as-gastronomico-db
          property: connectionString
